title: BookSHIFT
artist: PoorOjepse
description: This is my Pakitang-Gilas Website

email: bookshift@gmail.com
website: BookSHIFT.com
phoneno: (619) 287-5346

favicon: 'favicon.png'
logo: 'logo.jpg'

seo:
   rel-author: 'https://plus.google.com/u/0/+PoorOjepse/'
   rel-publisher: 'https://plus.google.com/u/0/+PoorOjepse/'

socials:
- {link: 'http://facebook.com/bookshift', icon: 'facebook'}
- {link: 'http://twitter.com/bookshift', icon: 'twitter'}
- {link: 'http://youtube.com/bookshift', icon: 'youtube'}

bone:
- {imgno: 'img1', img: 'bone-the-great-cow-race'}
- {imgno: 'img2', img: 'bone-tall-tales'}
- {imgno: 'img3', img: 'bone-the-dragonslayer'}

saga: 
- {img: 'saga-8'}
- {img: 'saga-13'}
- {img: 'saga-16'}

easttowest:
- {img: 'east-to-west-volume-3'}
- {img: 'east-to-west-volume-2'}
- {img: 'east-to-west-volume-6'}
